// Generate a synthetic stress fixture for v1.2.0 perf testing.
//
// Run with:  node scripts/genBigFixture.js [blockCount]
// Default:   60 blocks → ~720 lines, 540 className tokens covering every
//            shape the AST walker handles (plain, template, ternary, &&, ||,
//            concat, clsx string/object/array, cn alias).
//
// Tweak `blockCount` upward if you need ≥1000-line stress (e.g. 100 → 1200).
// The output file is overwritten — safe to regenerate.

const fs = require('fs');
const path = require('path');

const OUT = path.resolve(
  __dirname,
  '..',
  '..',
  'test-workspace',
  'src',
  'components',
  'BigFixture.jsx',
);
const NUM_BLOCKS = parseInt(process.argv[2] || '60', 10);

// Each entry produces one JSX line per block. The selectors used (`btn-base`,
// `btn-active`, `btn-disabled`, `is-open`, `is-closed`, `menu-open`,
// `menu-closed`) all exist in DynamicClassName.css, so F12/Hover hit a real
// rule and the test can verify reverse-nav too.
const SHAPES = [
  i => `<div className="btn-base btn-active">plain-${i}</div>`,
  i => `<div className={\`btn-base btn-\${${i}}\`}>tpl-prefix-${i}</div>`,
  i => `<div className={\`btn-base \${props.a${i} ? "btn-active" : ""}\`}>tpl-mixed-${i}</div>`,
  i => `<div className={props.b${i} && "btn-active"}>and-${i}</div>`,
  i => `<div className={props.c${i} ? "menu-open" : "menu-closed"}>ter-${i}</div>`,
  i => `<div className={"is-" + (props.d${i} ? "open" : "closed")}>cat-${i}</div>`,
  i => `<div className={clsx("btn-base", "btn-active")}>clsx-s-${i}</div>`,
  i => `<div className={clsx("btn-base", props.e${i} && "btn-active", { "btn-disabled": props.f${i} })}>clsx-mix-${i}</div>`,
  i => `<div className={cn("btn-base", "is-open")}>cn-${i}</div>`,
];

const lines = [
  `import React from "react";`,
  `import "./DynamicClassName.css";`,
  ``,
  `// Auto-generated by scripts/genBigFixture.js — DO NOT hand-edit.`,
  `// Stress fixture for v1.2.0 perf testing of the AST class-index walker.`,
  `// ${NUM_BLOCKS} blocks × ${SHAPES.length} className shapes = ${NUM_BLOCKS * SHAPES.length} tokens.`,
  ``,
  `const clsx = (...a) => a.filter(Boolean).join(" ");`,
  `const cn = clsx;`,
  ``,
  `export default function BigFixture(props) {`,
  `  return (`,
  `    <div id="dynamic-root">`,
];

for (let i = 0; i < NUM_BLOCKS; i++) {
  lines.push(`      {/* Block ${i} */}`);
  for (const fn of SHAPES) lines.push(`      ${fn(i)}`);
  lines.push(``);
}

lines.push(`    </div>`);
lines.push(`  );`);
lines.push(`}`);

const text = lines.join('\n') + '\n';
fs.writeFileSync(OUT, text);

const lineCount = text.split('\n').length;
const tokenCount = NUM_BLOCKS * SHAPES.length;
console.log(`Wrote ${OUT}`);
console.log(`  ${lineCount} lines, ${NUM_BLOCKS} blocks, ${tokenCount} className tokens`);
